# Generated by Django 4.1.6 on 2023-02-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('linkedIn_url', models.URLField()),
                ('github_url', models.URLField()),
                ('portfolio_url', models.URLField()),
                ('resume_url', models.URLField()),
                ('job_type', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=50)),
            ],
        ),
    ]
