# Generated by Django 4.1.6 on 2023-02-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelineapi', '0002_alter_techie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='techie',
            name='open_for_work',
            field=models.BooleanField(default=True),
        ),
    ]
